# Generated by Django 2.2.10 on 2020-05-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='show when the object is active.', verbose_name='is_active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the objects was created.', verbose_name='create_at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the objects was last updated.', verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(help_text='Date time on which the objects was deleted.', null=True, verbose_name='deleted_at')),
                ('created_by', models.PositiveIntegerField(help_text='created_by', null=True)),
                ('updated_by', models.PositiveIntegerField(help_text='updated_by', null=True)),
                ('deleted_by', models.PositiveIntegerField(help_text='deleted_by', null=True)),
                ('name', models.CharField(max_length=128, verbose_name='Rubro name')),
                ('description', models.TextField(blank=True, max_length=512)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/images/', verbose_name='image Category')),
                ('count_post', models.PositiveIntegerField(default=0)),
                ('count_craftman', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
