# Generated by Django 2.2.10 on 2020-05-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20200415_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count_craftman',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='count_post',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
