# Generated by Django 2.2.10 on 2020-05-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20200505_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/images/', verbose_name='image Category'),
        ),
    ]
