# Generated by Django 2.2.10 on 2020-03-03 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='show when the object is active.', verbose_name='is_deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the objects was created.', verbose_name='create_at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the objects was last updated.', verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(auto_now=True, help_text='Date time on which the objects was deleted.', verbose_name='updated_at')),
                ('created_by', models.PositiveIntegerField(help_text='created_by', null=True)),
                ('updated_by', models.PositiveIntegerField(help_text='updated_by', null=True)),
                ('deleted_by', models.PositiveIntegerField(help_text='deleted_by', null=True)),
                ('name', models.CharField(help_text='Temporal user name', max_length=256, verbose_name='name')),
                ('email', models.EmailField(error_messages={'unique': 'A user with  thise email already exists.'}, max_length=254, unique=True, verbose_name='email')),
                ('code_devide', models.CharField(blank=True, max_length=516)),
                ('is_verified', models.BooleanField(default=False, help_text='Set to true when the user have verified its email address.', verbose_name='verified')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_by', to='categories.Category'),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_by',
            field=models.PositiveIntegerField(help_text='created_by', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='deleted_by',
            field=models.PositiveIntegerField(help_text='deleted_by', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_by',
            field=models.PositiveIntegerField(help_text='updated_by', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.PositiveIntegerField(help_text='created_by', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_by',
            field=models.PositiveIntegerField(help_text='deleted_by', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('A', 'Admin'), ('B', 'Craftsman'), ('C', 'Client')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_by',
            field=models.PositiveIntegerField(help_text='updated_by', null=True),
        ),
    ]
