# Generated by Django 2.2.10 on 2020-04-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200404_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nit_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
