# Generated by Django 2.2.10 on 2020-05-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200415_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='deleted_at',
            field=models.DateTimeField(help_text='Date time on which the objects was deleted.', null=True, verbose_name='deleted_at'),
        ),
        migrations.AlterField(
            model_name='temporaluser',
            name='deleted_at',
            field=models.DateTimeField(help_text='Date time on which the objects was deleted.', null=True, verbose_name='deleted_at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(help_text='Date time on which the objects was deleted.', null=True, verbose_name='deleted_at'),
        ),
        migrations.AlterField(
            model_name='usertemporalpassword',
            name='deleted_at',
            field=models.DateTimeField(help_text='Date time on which the objects was deleted.', null=True, verbose_name='deleted_at'),
        ),
    ]
