# Generated by Django 2.2.10 on 2020-05-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200511_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='temporaluser',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='usertemporalpassword',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True, help_text='show when the object is active.', verbose_name='is_active'),
        ),
        migrations.AddField(
            model_name='temporaluser',
            name='active',
            field=models.BooleanField(default=True, help_text='show when the object is active.', verbose_name='is_active'),
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True, help_text='show when the object is active.', verbose_name='is_active'),
        ),
        migrations.AddField(
            model_name='usertemporalpassword',
            name='active',
            field=models.BooleanField(default=True, help_text='show when the object is active.', verbose_name='is_active'),
        ),
    ]
