from .departaments import DepartamentAdminViewSet
from .departaments import DepartamentViewSet
from .departaments import DepartamentListViewSet
from .provinces import ProvinceAdminViewSet
from .provinces import ProvinceViewSet
from .provinces import ProvinceListViewSet
from .municipalities import MunicipalityAdminViewSet
from .municipalities import MunicipalityViewSet
from .municipalities import MunicipalityListViewSet