# Generated by Django 2.2.10 on 2020-04-25 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0002_auto_20200416_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='show when the object is active.', verbose_name='is_deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the objects was created.', verbose_name='create_at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the objects was last updated.', verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(auto_now=True, help_text='Date time on which the objects was deleted.', verbose_name='updated_at')),
                ('created_by', models.PositiveIntegerField(help_text='created_by', null=True)),
                ('updated_by', models.PositiveIntegerField(help_text='updated_by', null=True)),
                ('deleted_by', models.PositiveIntegerField(help_text='deleted_by', null=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('ubicacion', models.TextField(max_length=512)),
                ('gps', models.CharField(max_length=10)),
                ('date_init', models.DateField()),
                ('date_end', models.DateField()),
                ('time_init', models.TimeField(null=True)),
                ('time_end', models.TimeField(null=True)),
                ('is_limited', models.BooleanField(default=False, help_text='limited fair can grow up a to fixed number of participant', verbose_name='limited')),
                ('participant_limit', models.PositiveIntegerField(default=0, help_text='If the fair is limited, this will be the limit on the number of participants')),
                ('reputation', models.FloatField(default=5.0, help_text="Fair's reputation based on crafts.")),
                ('publications', models.PositiveIntegerField(default=0)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('municipality', models.ForeignKey(help_text='municipality where fair stay', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fairs', to='maps.Municipality')),
                ('user', models.ForeignKey(help_text='creator of fair', on_delete=django.db.models.deletion.CASCADE, related_name='fairs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fair',
                'verbose_name_plural': 'Fairs',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='show when the object is active.', verbose_name='is_deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the objects was created.', verbose_name='create_at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the objects was last updated.', verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(auto_now=True, help_text='Date time on which the objects was deleted.', verbose_name='updated_at')),
                ('created_by', models.PositiveIntegerField(help_text='created_by', null=True)),
                ('updated_by', models.PositiveIntegerField(help_text='updated_by', null=True)),
                ('deleted_by', models.PositiveIntegerField(help_text='deleted_by', null=True)),
                ('user_description', models.TextField(blank=True, max_length=2048)),
                ('admin_description', models.TextField(blank=True, max_length=2048)),
                ('state', models.CharField(choices=[('AA', 'Aceptado'), ('PP', 'Pendiente'), ('RR', 'Rechazado')], default='PP', max_length=2, verbose_name='status_participant_choices')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fairs.Fair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FairMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='show when the object is active.', verbose_name='is_deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the objects was created.', verbose_name='create_at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the objects was last updated.', verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(auto_now=True, help_text='Date time on which the objects was deleted.', verbose_name='updated_at')),
                ('created_by', models.PositiveIntegerField(help_text='created_by', null=True)),
                ('updated_by', models.PositiveIntegerField(help_text='updated_by', null=True)),
                ('deleted_by', models.PositiveIntegerField(help_text='deleted_by', null=True)),
                ('img_huge', models.ImageField(default='', max_length=255, upload_to='img/fair/huge/', verbose_name='Image huge')),
                ('img_standar', models.ImageField(default='', max_length=255, upload_to='img/fair/standar/', verbose_name='Image standar')),
                ('img_small', models.ImageField(default='', max_length=255, upload_to='img/fair/small/', verbose_name='Image small')),
                ('order', models.PositiveIntegerField(default=1)),
                ('fair', models.ForeignKey(help_text="fair's media", on_delete=django.db.models.deletion.CASCADE, related_name='fairmedias', to='fairs.Fair')),
            ],
            options={
                'verbose_name': 'fair media',
                'verbose_name_plural': 'fair media',
            },
        ),
    ]
