# Generated by Django 2.2.10 on 2020-05-27 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0001_initial'),
        ('fairs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participant',
            name='fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fairs.Fair'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fairmedia',
            name='fair',
            field=models.ForeignKey(help_text="fair's media", on_delete=django.db.models.deletion.CASCADE, related_name='fairmedias', to='fairs.Fair'),
        ),
        migrations.AddField(
            model_name='fair',
            name='municipality',
            field=models.ForeignKey(help_text='municipality where fair stay', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fairs', to='maps.Municipality'),
        ),
        migrations.AddField(
            model_name='fair',
            name='user',
            field=models.ForeignKey(help_text='creator of fair', on_delete=django.db.models.deletion.CASCADE, related_name='fairs', to=settings.AUTH_USER_MODEL),
        ),
    ]
