# Generated by Django 2.2.10 on 2020-04-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='state',
            field=models.CharField(choices=[('AA', 'Accepted'), ('PP', 'Pending'), ('RR', 'Denied'), ('DD', 'Declined')], default='PP', max_length=2, verbose_name='status_participant_choices'),
        ),
    ]
