# Generated by Django 2.2.10 on 2020-04-16 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='show when the object is active.', verbose_name='is_deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the objects was created.', verbose_name='create_at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the objects was last updated.', verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(auto_now=True, help_text='Date time on which the objects was deleted.', verbose_name='updated_at')),
                ('created_by', models.PositiveIntegerField(help_text='created_by', null=True)),
                ('updated_by', models.PositiveIntegerField(help_text='updated_by', null=True)),
                ('deleted_by', models.PositiveIntegerField(help_text='deleted_by', null=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('ubicacion', models.TextField(max_length=512)),
                ('gps', models.CharField(max_length=10)),
                ('reputation', models.FloatField(default=5.0, help_text="Store's reputation based on crafts.")),
                ('publications', models.PositiveIntegerField(default=0)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(help_text='User is property of store', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='StoreMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='show when the object is active.', verbose_name='is_deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the objects was created.', verbose_name='create_at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the objects was last updated.', verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(auto_now=True, help_text='Date time on which the objects was deleted.', verbose_name='updated_at')),
                ('created_by', models.PositiveIntegerField(help_text='created_by', null=True)),
                ('updated_by', models.PositiveIntegerField(help_text='updated_by', null=True)),
                ('deleted_by', models.PositiveIntegerField(help_text='deleted_by', null=True)),
                ('img_huge', models.ImageField(default='', max_length=255, upload_to='img/store/huge/', verbose_name='Image huge')),
                ('img_standar', models.ImageField(default='', max_length=255, upload_to='img/store/standar/', verbose_name='Image standar')),
                ('img_small', models.ImageField(default='', max_length=255, upload_to='img/store/small/', verbose_name='Image small')),
                ('order', models.PositiveIntegerField(default=1)),
                ('store', models.ForeignKey(help_text="store's media", on_delete=django.db.models.deletion.CASCADE, related_name='media', to='stores.Store')),
            ],
            options={
                'verbose_name': 'store media',
                'verbose_name_plural': 'store media',
            },
        ),
    ]
