# Generated by Django 2.2.10 on 2020-04-17 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20200416_2111'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='municipality',
            field=models.ForeignKey(help_text='municipality where store stay', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='maps.Municipality'),
        ),
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.ForeignKey(help_text='User is property of store', on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storemedia',
            name='store',
            field=models.ForeignKey(help_text="store's media", on_delete=django.db.models.deletion.CASCADE, related_name='storemedias', to='stores.Store'),
        ),
    ]
