# Generated by Django 2.2.10 on 2020-05-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20200511_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='ubicacion',
            new_name='location',
        ),
    ]
