# Generated by Django 2.2.10 on 2020-05-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20200416_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='deleted_at',
            field=models.DateTimeField(help_text='Date time on which the objects was deleted.', null=True, verbose_name='deleted_at'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='deleted_at',
            field=models.DateTimeField(help_text='Date time on which the objects was deleted.', null=True, verbose_name='deleted_at'),
        ),
        migrations.AlterField(
            model_name='province',
            name='deleted_at',
            field=models.DateTimeField(help_text='Date time on which the objects was deleted.', null=True, verbose_name='deleted_at'),
        ),
    ]
