# Generated by Django 2.2.10 on 2020-04-30 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='show when the object is active.', verbose_name='is_deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the objects was created.', verbose_name='create_at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the objects was last updated.', verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(auto_now=True, help_text='Date time on which the objects was deleted.', verbose_name='updated_at')),
                ('created_by', models.PositiveIntegerField(help_text='created_by', null=True)),
                ('updated_by', models.PositiveIntegerField(help_text='updated_by', null=True)),
                ('deleted_by', models.PositiveIntegerField(help_text='deleted_by', null=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('cuantitie', models.PositiveIntegerField(default=None, null=True)),
                ('state', models.CharField(choices=[('AV', 'Available'), ('SO', 'Sold')], default='AV', max_length=2, verbose_name='status_post_choices')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='show when the object is active.', verbose_name='is_deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the objects was created.', verbose_name='create_at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the objects was last updated.', verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(auto_now=True, help_text='Date time on which the objects was deleted.', verbose_name='updated_at')),
                ('created_by', models.PositiveIntegerField(help_text='created_by', null=True)),
                ('updated_by', models.PositiveIntegerField(help_text='updated_by', null=True)),
                ('deleted_by', models.PositiveIntegerField(help_text='deleted_by', null=True)),
                ('img_huge', models.ImageField(default='', max_length=255, upload_to='img/post/huge/', verbose_name='Image huge')),
                ('img_standar', models.ImageField(default='', max_length=255, upload_to='img/post/standar/', verbose_name='Image standar')),
                ('img_small', models.ImageField(default='', max_length=255, upload_to='img/post/small/', verbose_name='Image small')),
                ('img_thumbnail', models.ImageField(default='', max_length=255, upload_to='img/post/thumbnail/', verbose_name='Image thumbnail')),
                ('order', models.PositiveIntegerField(default=1)),
                ('post', models.ForeignKey(help_text="post's media", on_delete=django.db.models.deletion.CASCADE, related_name='postmedias', to='posts.Post')),
            ],
            options={
                'verbose_name': 'post media',
                'verbose_name_plural': 'post media',
            },
        ),
    ]
